CREATE TABLE IF NOT EXISTS tx_admins (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 session_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tx_news (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 image VARCHAR(190) NOT NULL DEFAULT '',
 status VARCHAR(12) NOT NULL DEFAULT 'draft',
 published_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 INDEX tx_news_public (status, published_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tx_news_translations (
 news_id INT UNSIGNED NOT NULL,
 lang VARCHAR(3) NOT NULL,
 title VARCHAR(180) NOT NULL,
 body MEDIUMTEXT NOT NULL,
 PRIMARY KEY (news_id, lang),
 CONSTRAINT tx_news_translation_fk FOREIGN KEY (news_id) REFERENCES tx_news(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tx_login_attempts (
 ip_hash CHAR(64) NOT NULL PRIMARY KEY,
 attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 window_started BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
